<?php

/**
 * @file
 * kmbs theme file.
 */

 use Drupal\Component\Utility\Html;

 /**
  * Preprocess variables for html templates.
  * @param $variables
  */
 function HOOK_preprocess_html(&$variables) {
   $variables['path_info']['args'] = FALSE;
   $path = \Drupal::request()->getPathInfo();
   $path_args = explode('/', $path);
   if (count($path_args) >= 3) {
     $variables['path_info']['args'] = Html::cleanCssIdentifier(ltrim($path, '/'));
   }
 }
